name: nano_mock

description: >-
  A lightweight mock library without any dependencies or requirements to use
  code generation.

version: 1.0.1

repository: https://github.com/oborgen/nano_mock

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
