name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Install Flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.2'

      # Disable Flutter analytics.
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      # Install dependencies.
      - name: Install dependencies
        run: dart pub get

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
      
      # Call flutter test and collect coverage.
      - name: Run tests
        run: flutter test --coverage

      # Publish coverage information to codecov.io.
      - name: Publish coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
